### ISSUE TITLE
Readme contains D3.js logo

### ISSUE THREAD

**Issue by edeno** [NeuralProsthesisLab/unlock#43]
Probably just a copy paste issue.

**Comment by jpercent** [comment]
Hey Eric, thanks for looking at the code. Are you planning to use it for anything? I've been using a bunch of the pieces in production on other projects and they've come a long way from what is in this prototype. I'm happy to talk through things. My email is james at shift5 dot net.

As for the d3 image... I wanted an image there, but couldn't find one that I liked. I'm not a graphic artist. If you rotate the d3 image, it almost looks like a pad-lock! Anyway, I just never got around to changing it. I didn't think anyone would notice since there were no programmers developing on the framework!

**Comment by edeno** [comment]
I'm loosely affiliated with Frank Guenther's lab. Not planning on using the
code for anything but was browsing and curious.

Just noticed the D3 logo and know that the D3 developer is sensitive to
using the D3 logo for things. It's probably not a big deal, but I would be
wary of using it without permission is all.

**Comment by jpercent** [comment]
Feel free to cahage it.
